### ISSUE TITLE
Could not open socket for RMP...

### ISSUE THREAD

**Issue by somebodyus** [StanleyInnovation/segway_v3_robot#8] opened 2016-10-14 12:11 UTC
I have exactly follow the procedure, but I got an error:

Could not open socket for RMP...

**Comment by PatrickHussey** [comment] 2016-10-14 14:00
Make sure you can ping the platform. If you cannot then your ethernet settings are incorrect. You usually get this error when the NIC or wireless connected to the platform is not on the 10.66.171.XXX network.

**Comment by somebodyus** [comment] 2016-10-15 02:26
I am using a switch.
Do I need to use a router and assign fixed IP address in the router to each device?

**Comment by PatrickHussey** [comment] 2016-10-15 02:33
Depends on the setup. There is not enough information 

Here is a good resource for ROS networking
http://wiki.ros.org/ROS/NetworkSetup

**Comment by somebodyus** [comment] 2016-10-15 03:28
Is there an embedded system with an network card in the platform?  The firmware has fixed the IP to 10.66.171.5?

Another question is why we need to set the wlan card to a fixed IP in the 10.66.172.xx network? Why not 10.66.171.xx?

**Comment by PatrickHussey** [comment] 2016-10-15 04:13
should be like this

![image](https://cloud.githubusercontent.com/assets/9217506/19407303/2cfe8bd0-926c-11e6-8d01-a427b771cc2d.png)

**Comment by somebodyus** [comment] 2016-10-15 05:38
Can the attached configuration work?

**Comment by somebodyus** [comment] 2016-10-15 05:39
Can the attached configuration work? How to set

![Uploading snap.PNG…]()

**Comment by somebodyus** [comment] 2016-10-15 05:48
Sorry for clicking the close button.

I have a PC with 3 NICs. The wired one connecting to robot is 10.66.171.4. A wireless one is set to 10.66.172.4, it does not work. The other wireless one is dhcp which is connecting to the internet.

How can I set the ROS_MASTER_URI and ROS_HOST_NAME variables?

**Comment by PatrickHussey** [comment] 2016-10-15 12:55
You need the package segway_v3_network in the top level repo and set those in the file in the env-hooks folder and recompile

Everything should just be on the 10.66.171.xxx the instructions need to be updated.

**Comment by somebodyus** [comment] 2016-10-17 02:29
I can ping the platform 10.66.171.5, but still cannot get connected.

**Comment by PatrickHussey** [comment] 2016-10-17 03:26
What are the network settings in the package segway_v3_network?

It should have env-hooks that get compiled into the workspace.

Try opening a terminal, sourcing the workspace, and echoing the env variables ROS_IP and ROS_MASTER_URI; should return the NIC connected to a switch or router that has the robot plugged into it

**Comment by PatrickHussey** [comment] 2016-10-17 13:12
I assume this is resolved since you are asking about teleop? Can you confirm and close this.

**Comment by somebodyus** [comment] 2016-10-17 13:21
Yes.  Problem solved by manually set the ROS_MASTER_URI and ROS_IP in the terminal. 
How can I avoid setting the two variables at each time when I launch `roslaunch segway_bringup stanley_innovation_system.launch`?

**Comment by PatrickHussey** [comment] 2016-10-17 13:27
You need to set them in 50.segway_network_config.sh which is an env-hook file for catkin. Once you have compiled changing it is source does nothing even if you re-compile. You need to do one of 2 things to get changes in source to stick after the code is compiled:

**after making changed to src/segway_v3_network/env-hooks/50.segway_network_config.sh**

1. Delete the devel and build directories in the workspace and re-compile
2. Copy that file into /devel/catkin/etc/profile.d to overwrite the one that was originally compiled

I am rolling in a bunch of changes today which will include not needing to recompile or copy that file to change the network settings. But for now that is how it gets done.

**Comment by PatrickHussey** [comment] 2016-10-17 13:30
Please close once you have confirmed that's what needs to be done

**Closed** 2016-10-17 18:49 UTC
